# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Saara Satokangas
title: Kaupallinen nörtti 
email: saara.satokangas[a]helsinki.fi

darkmode: false

# Social links
github_username: saarasat
linkedin_username: saarasatokangas

# About Section
about_profile_image: images/profiili.jpg
about_content: | # this will include new lines to allow paragraphs
  
  Olen median ja markkinoinnin ammattilainen, joka on hurahtanut ohjelmistojen ja koodaukseen maailmaan.

  Ekonomiksi olen opiskellut rakkaassa kotikaupungissani Oulussa, jonka jälkeen toimin viitisen vuotta digitaalisen
  markkinoinnin tuotekehityksessä Suomessa ja ulkomailla. 

  Voimistuva halu työskennellä teknisemmän puolen kanssa vei mukanaan,
  ja nyt olen kandivaiheen loppusuoralla Helsingin yliopiston tietojenkäsittelytieteissä.
  
  Motivoidun eniten, kun saan oppia uutta ja tehdä jotain, 
  josta on aidosti hyötyä, 
  oli se sitten asiakkaalle, työkaverille tai loppukäyttäjälle.

  Parhaimmillani olenkin siellä, 
  missä kohderyhmän tarpeet ja tekniset ratkaisut kohtaavat.


# Experience Section
experience_title: Työkokemus

# Education Section
education_title: Koulutus

# More Section
technology_title: Kieli- ja teknologiataidot

# More Section
achievements_title: Harrastuksia ja järjestötoimintaa 
  
# Footer
footer_show_references: true

remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
